In [1]:
#importing the important library
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [2]:
#connecting the dataset
df=pd.read_csv('movies.csv')

In [3]:
#checkinng the heads of the data 
df.head()

,names,date_x,score,genre,overview,crew,orig_title,status,orig_lang,budget_x,revenue,country
0,Creed III,03/02/2023,73.0,"Drama, Action","After dominating the boxing world, Adonis Cree...","Michael B. Jordan, Adonis Creed, Tessa Thompso...",Creed III,Released,English,75000000.0,2.716167e+08,AU
1,Avatar: The Way of Water,12/15/2022,78.0,"Science Fiction, Adventure, Action",Set more than a decade after the events of the...,"Sam Worthington, Jake Sully, Zoe Saldaña, Neyt...",Avatar: The Way of Water,Released,English,460000000.0,2.316795e+09,AU
2,The Super Mario Bros. Movie,04/05/2023,76.0,"Animation, Adventure, Family, Fantasy, Comedy","While working underground to fix a water main,...","Chris Pratt, Mario (voice), Anya Taylor-Joy, P...",The Super Mario Bros. Movie,Released,English,100000000.0,7.244590e+08,AU
3,Mummies,01/05/2023,70.0,"Animation, Comedy, Family, Adventure, Fantasy","Through a series of unfortunate events, three ...","Óscar Barberán, Thut (voice), Ana Esther Albor...",Momias,Released,"Spanish, Castilian",12300000.0,3.420000e+07,AU
4,Supercell,03/17/2023,61.0,Action,Good-hearted teenager William always lived in ...,"Skeet Ulrich, Roy Cameron, Anne Heche, Dr Quin...",Supercell,Released,English,77000000.0,3.409420e+08,US

In [4]:
#checking the shape and size of the data
df.shape

(10178, 12)

In [5]:
#checkng the column name
df.columns

Index(['names', 'date_x', 'score', 'genre', 'overview', 'crew', 'orig_title',
       'status', 'orig_lang', 'budget_x', 'revenue', 'country'],
      dtype='object')

In [6]:
#checking the info of the dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10178 entries, 0 to 10177
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   names       10178 non-null  object
 1   date_x      10178 non-null  object
 2   score       10178 non-null  float64
 3   genre       10093 non-null  object
 4   overview    10178 non-null  object
 5   crew        10122 non-null  object
 6   orig_title  10178 non-null  object
 7   status      10178 non-null  object
 8   orig_lang   10178 non-null  object
 9   budget_x    10178 non-null  float64
 10  revenue     10178 non-null  float64
 11  country     10178 non-null  object
dtypes: float64(3), object(9)
memory usage: 954.3+ KB

In [7]:
#checking the null values
df.isnull().sum()

names          0
date_x         0
score          0
genre         85
overview       0
crew          56
orig_title     0
status         0
orig_lang      0
budget_x       0
revenue        0
country        0
dtype: int64

In [8]:
#checkng the duplicates 
df.duplicated().sum()

np.int64(0)

In [9]:
#Selecting the columnds that are needed
df=df[['names','genre','overview','crew','score','orig_lang']]

In [10]:
df.head()

,names,genre,overview,crew,score,orig_lang
0,Creed III,"Drama, Action","After dominating the boxing world, Adonis Cree...","Michael B. Jordan, Adonis Creed, Tessa Thompso...",73.0,English
1,Avatar: The Way of Water,"Science Fiction, Adventure, Action",Set more than a decade after the events of the...,"Sam Worthington, Jake Sully, Zoe Saldaña, Neyt...",78.0,English
2,The Super Mario Bros. Movie,"Animation, Adventure, Family, Fantasy, Comedy","While working underground to fix a water main,...","Chris Pratt, Mario (voice), Anya Taylor-Joy, P...",76.0,English
3,Mummies,"Animation, Comedy, Family, Adventure, Fantasy","Through a series of unfortunate events, three ...","Óscar Barberán, Thut (voice), Ana Esther Albor...",70.0,"Spanish, Castilian"
4,Supercell,Action,Good-hearted teenager William always lived in ...,"Skeet Ulrich, Roy Cameron, Anne Heche, Dr Quin...",61.0,English

In [11]:
df.shape

(10178, 6)

In [12]:
df.isnull().sum()

names         0
genre        85
overview      0
crew         56
score         0
orig_lang     0
dtype: int64

In [13]:
#Removing the null values from the columns 
df['genre'] = df['genre'].fillna('')
df['crew'] = df['crew'].fillna('')

In [14]:
df.isnull().sum()

names        0
genre        0
overview     0
crew         0
score        0
orig_lang    0
dtype: int64

In [15]:
#combining the all the columns
df["tags"]=df["genre"] + " " + df["overview"] + " " + df["crew"]

In [16]:
df.head()

,names,genre,overview,crew,score,orig_lang,tags
0,Creed III,"Drama, Action","After dominating the boxing world, Adonis Cree...","Michael B. Jordan, Adonis Creed, Tessa Thompso...",73.0,English,"Drama, Action After dominating the boxing worl..."
1,Avatar: The Way of Water,"Science Fiction, Adventure, Action",Set more than a decade after the events of the...,"Sam Worthington, Jake Sully, Zoe Saldaña, Neyt...",78.0,English,"Science Fiction, Adventure, Action Set more th..."
2,The Super Mario Bros. Movie,"Animation, Adventure, Family, Fantasy, Comedy","While working underground to fix a water main,...","Chris Pratt, Mario (voice), Anya Taylor-Joy, P...",76.0,English,"Animation, Adventure, Family, Fantasy, Comedy ..."
3,Mummies,"Animation, Comedy, Family, Adventure, Fantasy","Through a series of unfortunate events, three ...","Óscar Barberán, Thut (voice), Ana Esther Albor...",70.0,"Spanish, Castilian","Animation, Comedy, Family, Adventure, Fantasy ..."
4,Supercell,Action,Good-hearted teenager William always lived in ...,"Skeet Ulrich, Roy Cameron, Anne Heche, Dr Quin...",61.0,English,Action Good-hearted teenager William always li...

In [19]:
#converting tags into numbers
df['tags'][3]

'Animation,\xa0Comedy,\xa0Family,\xa0Adventure,\xa0Fantasy Through a series of unfortunate events, three mummies end up in present-day London and embark on a wacky and hilarious journey in search of an old ring belonging to the Royal Family, stolen by ambitious archaeologist Lord Carnaby. Óscar Barberán, Thut (voice), Ana Esther Alborg, Nefer (voice), Luis Pérez Reina, Carnaby (voice), María Luisa Solá, Madre (voice), Jaume Solà, Sekhem (voice), José Luis Mediavilla, Ed (voice), José Javier Serrano Rodríguez, Danny (voice), Aleix Estadella, Dennis (voice), María Moscardó, Usi (voice)'

In [20]:
#removing the stopwords
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import re

In [21]:
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\ayush\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\ayush\AppData\Roaming\nltk_data...

True

In [23]:
stop_words=set(stopwords.words('english'))
lemmatizer=WordNetLemmatizer()

In [26]:
def preprocess_text(text):
    #lowercase
    text=str(text).lower()
    #removd the punctuations
    text = re.sub(r'[^a-zA-Z\s]', '', text)

    words=text.split()
    #remove stopwords
    words=[word for word in words if word not in stop_words]

    #lemmatize
    words=[lemmatizer.lemmatize(word) for word in words]

    return " ".join(words)

In [27]:
df['tags']=df['tags'].apply(preprocess_text)

In [28]:
df['tags'][3]

'animation comedy family adventure fantasy series unfortunate event three mummy end presentday london embark wacky hilarious journey search old ring belonging royal family stolen ambitious archaeologist lord carnaby scar barbern thut voice ana esther alborg nefer voice luis prez reina carnaby voice mara luisa sol madre voice jaume sol sekhem voice jos luis mediavilla ed voice jos javier serrano rodrguez danny voice aleix estadella dennis voice mara moscard usi voice'

In [29]:
#removing the missingg index
df=df.reset_index(drop=True)

In [32]:
#knowing the index
indices=pd.Series(df.index,index=df['names']).drop_duplicates()
indices

names
Creed III                                      0
Avatar: The Way of Water                       1
The Super Mario Bros. Movie                    2
Mummies                                        3
Supercell                                      4
                                           ...
20th Century Women                         10173
Delta Force 2: The Colombian Connection    10174
The Russia House                           10175
Darkman II: The Return of Durant           10176
The Swan Princess: A Royal Wedding         10177
Length: 10178, dtype: int64

In [34]:
#using tfidf 
from sklearn.feature_extraction.text import TfidfVectorizer

In [40]:
tfidf=TfidfVectorizer(max_features=15000,ngram_range=(1,2),stop_words='english')      #ngram is used to vetorize the connected words

In [43]:
#creating a matrix that will arrange the format
tfidf_matrix=tfidf.fit_transform(df['tags'])

In [44]:
tfidf_matrix

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 513861 stored elements and shape (10178, 15000)>

In [45]:
#using cosine similarities
from sklearn.metrics.pairwise import cosine_similarity

In [50]:
def recommend(names,n=10):
    if names not in indices:
        return['Movie not found']
    
    idx=indices[names]
    sim_score=cosine_similarity(tfidf_matrix[idx],tfidf_matrix).flatten()
    similar_idx=sim_score.argsort()[::-1][1:n+1]
    return df['names'].iloc[similar_idx]

In [59]:
recommend('Scooby-Doo',5)

2683    Scooby-Doo 2: Monsters Unleashed
7702           Scooby-Doo! Frankencreepy
2151                              Scoob!
5559       Scooby-Doo! Shaggy's Showdown
4410      Scooby-Doo! The Mystery Begins
Name: names, dtype: object

In [60]:
#creating pickle files
import pickle

pickle.dump(tfidf_matrix,open('tfidf_matrix.pkl','wb'))

pickle.dump(indices,open('indices.pkl','wb'))

df.to_pickle('df.pkl')

pickle.dump(tfidf,open('tdidf.pkl','wb'))